apiVersion: v1
kind: Service
metadata:
  name: recipe-manager-service
spec:
  selector:
    app: recipe-manager-app
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 5050 
  type: LoadBalancer
