apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-manager-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-manager-app
  template:
    metadata:
      labels:
        app: recipe-manager-app
    spec:
      containers:
      - name: project1-yujie
        image: cyujie/recipe-docker-img:v4
        ports:
        - containerPort: 5050  

