global:
  scrape_interval: 15s  # Scrape every 15 seconds
  evaluation_interval: 15s  # Evaluate every 15 seconds

scrape_configs:
  # Monitor Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Monitor Recipe Manager App
  - job_name: "recipe-manager"
    metrics_path: "/metrics"  # Ensures only Prometheus data is scraped
    static_configs:
      - targets: ["localhost:5050"]
